// Peat Sidecar gRPC Service
// Exposes peat-protocol/peat-mesh as a gRPC API for co-located applications.
//
// Copyright 2026 Defense Unicorns
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: peat/sidecar/v1/sidecar.proto

package sidecarv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeatSidecar_GetStatus_FullMethodName                    = "/peat.sidecar.v1.PeatSidecar/GetStatus"
	PeatSidecar_ConnectPeer_FullMethodName                  = "/peat.sidecar.v1.PeatSidecar/ConnectPeer"
	PeatSidecar_DisconnectPeer_FullMethodName               = "/peat.sidecar.v1.PeatSidecar/DisconnectPeer"
	PeatSidecar_ListPeers_FullMethodName                    = "/peat.sidecar.v1.PeatSidecar/ListPeers"
	PeatSidecar_PutDocument_FullMethodName                  = "/peat.sidecar.v1.PeatSidecar/PutDocument"
	PeatSidecar_GetDocument_FullMethodName                  = "/peat.sidecar.v1.PeatSidecar/GetDocument"
	PeatSidecar_DeleteDocument_FullMethodName               = "/peat.sidecar.v1.PeatSidecar/DeleteDocument"
	PeatSidecar_ListDocuments_FullMethodName                = "/peat.sidecar.v1.PeatSidecar/ListDocuments"
	PeatSidecar_PutNode_FullMethodName                      = "/peat.sidecar.v1.PeatSidecar/PutNode"
	PeatSidecar_GetNodes_FullMethodName                     = "/peat.sidecar.v1.PeatSidecar/GetNodes"
	PeatSidecar_PutCell_FullMethodName                      = "/peat.sidecar.v1.PeatSidecar/PutCell"
	PeatSidecar_GetCells_FullMethodName                     = "/peat.sidecar.v1.PeatSidecar/GetCells"
	PeatSidecar_PutTrack_FullMethodName                     = "/peat.sidecar.v1.PeatSidecar/PutTrack"
	PeatSidecar_GetTracks_FullMethodName                    = "/peat.sidecar.v1.PeatSidecar/GetTracks"
	PeatSidecar_PutCommand_FullMethodName                   = "/peat.sidecar.v1.PeatSidecar/PutCommand"
	PeatSidecar_GetCommands_FullMethodName                  = "/peat.sidecar.v1.PeatSidecar/GetCommands"
	PeatSidecar_Subscribe_FullMethodName                    = "/peat.sidecar.v1.PeatSidecar/Subscribe"
	PeatSidecar_StartSync_FullMethodName                    = "/peat.sidecar.v1.PeatSidecar/StartSync"
	PeatSidecar_StopSync_FullMethodName                     = "/peat.sidecar.v1.PeatSidecar/StopSync"
	PeatSidecar_GetSyncStats_FullMethodName                 = "/peat.sidecar.v1.PeatSidecar/GetSyncStats"
	PeatSidecar_SendAttachments_FullMethodName              = "/peat.sidecar.v1.PeatSidecar/SendAttachments"
	PeatSidecar_GetAttachmentDistribution_FullMethodName    = "/peat.sidecar.v1.PeatSidecar/GetAttachmentDistribution"
	PeatSidecar_SubscribeAttachmentBundle_FullMethodName    = "/peat.sidecar.v1.PeatSidecar/SubscribeAttachmentBundle"
	PeatSidecar_CancelAttachmentDistribution_FullMethodName = "/peat.sidecar.v1.PeatSidecar/CancelAttachmentDistribution"
	PeatSidecar_SetCollectionConfig_FullMethodName          = "/peat.sidecar.v1.PeatSidecar/SetCollectionConfig"
	PeatSidecar_GetCollectionConfig_FullMethodName          = "/peat.sidecar.v1.PeatSidecar/GetCollectionConfig"
	PeatSidecar_ListCollectionConfigs_FullMethodName        = "/peat.sidecar.v1.PeatSidecar/ListCollectionConfigs"
)

// PeatSidecarClient is the client API for PeatSidecar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PeatSidecar exposes Peat mesh participation to co-located applications
// over gRPC (Unix socket or TCP). The sidecar is a full CRDT mesh participant;
// client applications interact with it to read/write shared state.
type PeatSidecarClient interface {
	// GetStatus returns the current state of the sidecar node.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// ConnectPeer establishes an authenticated connection to a mesh peer.
	ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error)
	// DisconnectPeer drops the connection to a peer.
	DisconnectPeer(ctx context.Context, in *DisconnectPeerRequest, opts ...grpc.CallOption) (*DisconnectPeerResponse, error)
	// ListPeers returns currently connected peers.
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error)
	// PutDocument creates or updates a document in a collection.
	PutDocument(ctx context.Context, in *PutDocumentRequest, opts ...grpc.CallOption) (*PutDocumentResponse, error)
	// GetDocument retrieves a document by collection and ID.
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	// DeleteDocument removes a document from a collection.
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	// ListDocuments lists all document IDs in a collection.
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	PutNode(ctx context.Context, in *PutNodeRequest, opts ...grpc.CallOption) (*PutNodeResponse, error)
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
	PutCell(ctx context.Context, in *PutCellRequest, opts ...grpc.CallOption) (*PutCellResponse, error)
	GetCells(ctx context.Context, in *GetCellsRequest, opts ...grpc.CallOption) (*GetCellsResponse, error)
	PutTrack(ctx context.Context, in *PutTrackRequest, opts ...grpc.CallOption) (*PutTrackResponse, error)
	GetTracks(ctx context.Context, in *GetTracksRequest, opts ...grpc.CallOption) (*GetTracksResponse, error)
	PutCommand(ctx context.Context, in *PutCommandRequest, opts ...grpc.CallOption) (*PutCommandResponse, error)
	GetCommands(ctx context.Context, in *GetCommandsRequest, opts ...grpc.CallOption) (*GetCommandsResponse, error)
	// Subscribe streams document changes across all or filtered collections.
	//
	// The server sends an initial snapshot of all currently-stored matching
	// documents as CHANGE_TYPE_UPSERT events, then streams live changes.
	// Clients can distinguish snapshot from live events by consuming until
	// the server indicates readiness, or by treating all Upserts idempotently.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DocumentChange], error)
	// StartSync begins CRDT synchronization with connected peers.
	StartSync(ctx context.Context, in *StartSyncRequest, opts ...grpc.CallOption) (*StartSyncResponse, error)
	// StopSync pauses synchronization.
	StopSync(ctx context.Context, in *StopSyncRequest, opts ...grpc.CallOption) (*StopSyncResponse, error)
	// GetSyncStats returns current synchronization statistics.
	GetSyncStats(ctx context.Context, in *GetSyncStatsRequest, opts ...grpc.CallOption) (*GetSyncStatsResponse, error)
	// SendAttachments ingests one or more local files and queues them for
	// distribution to the specified scope. Each file is validated (size, hash,
	// path inside an allowlisted root) before any blob is created — partial
	// ingestion is not allowed. Returns synchronously with handles; transfer
	// happens asynchronously.
	//
	// Safety default: with no `--attachment-root` configured on peat-node, this
	// RPC returns UNIMPLEMENTED. Operators must consciously opt in by naming
	// the roots that may be read.
	SendAttachments(ctx context.Context, in *SendAttachmentsRequest, opts ...grpc.CallOption) (*SendAttachmentsResponse, error)
	// GetAttachmentDistribution returns the current status of a single
	// distribution by its ID. Returns NOT_FOUND with the offending
	// distribution_id in the error detail when the ID is unknown.
	GetAttachmentDistribution(ctx context.Context, in *GetAttachmentDistributionRequest, opts ...grpc.CallOption) (*GetAttachmentDistributionResponse, error)
	// SubscribeAttachmentBundle streams progress updates for every distribution
	// in a bundle until all reach a terminal state or the client disconnects.
	//
	// Late-subscribe semantics (for crash-recovery):
	//   - All-terminal at subscribe time (every distribution already in
	//     COMPLETED / FAILED / CANCELLED): the server emits exactly one
	//     AttachmentProgress snapshot per distribution carrying that terminal
	//     state, then closes the stream.
	//   - Mixed state at subscribe time (some distributions already terminal,
	//     others still PENDING / IN_PROGRESS): the server emits one snapshot
	//     for each already-terminal distribution first, then streams live
	//     progress updates for the in-flight distributions, then closes once
	//     every distribution has reached a terminal state.
	//   - All-live at subscribe time (no terminal distributions yet): live
	//     streaming only — no synthetic snapshots — until terminal close.
	//
	// The late-subscribe contract covers *client* crashes. A *server*
	// (peat-node) restart drops the in-memory handle table; resubscribing to
	// a pre-restart bundle_id returns NOT_FOUND.
	SubscribeAttachmentBundle(ctx context.Context, in *SubscribeAttachmentBundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AttachmentProgress], error)
	// CancelAttachmentDistribution requests cancellation of an in-flight
	// distribution. Best-effort; already-transferred bytes on receivers are
	// not rolled back. Returns NOT_FOUND when distribution_id is unknown.
	CancelAttachmentDistribution(ctx context.Context, in *CancelAttachmentDistributionRequest, opts ...grpc.CallOption) (*CancelAttachmentDistributionResponse, error)
	// SetCollectionConfig persists deletion-policy and TTL settings for a named
	// collection. Settings survive node restarts. Applying a new config to an
	// existing collection replaces the prior config wholesale.
	SetCollectionConfig(ctx context.Context, in *SetCollectionConfigRequest, opts ...grpc.CallOption) (*SetCollectionConfigResponse, error)
	// GetCollectionConfig returns the explicit config for a collection.
	// Returns NOT_FOUND when no config has been set (the default policy applies).
	GetCollectionConfig(ctx context.Context, in *GetCollectionConfigRequest, opts ...grpc.CallOption) (*GetCollectionConfigResponse, error)
	// ListCollectionConfigs returns all explicitly configured collections.
	// Collections using the default policy are not included.
	ListCollectionConfigs(ctx context.Context, in *ListCollectionConfigsRequest, opts ...grpc.CallOption) (*ListCollectionConfigsResponse, error)
}

type peatSidecarClient struct {
	cc grpc.ClientConnInterface
}

func NewPeatSidecarClient(cc grpc.ClientConnInterface) PeatSidecarClient {
	return &peatSidecarClient{cc}
}

func (c *peatSidecarClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectPeerResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_ConnectPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) DisconnectPeer(ctx context.Context, in *DisconnectPeerRequest, opts ...grpc.CallOption) (*DisconnectPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectPeerResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_DisconnectPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeersResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) PutDocument(ctx context.Context, in *PutDocumentRequest, opts ...grpc.CallOption) (*PutDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutDocumentResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_PutDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) PutNode(ctx context.Context, in *PutNodeRequest, opts ...grpc.CallOption) (*PutNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutNodeResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_PutNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) PutCell(ctx context.Context, in *PutCellRequest, opts ...grpc.CallOption) (*PutCellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutCellResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_PutCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) GetCells(ctx context.Context, in *GetCellsRequest, opts ...grpc.CallOption) (*GetCellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCellsResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_GetCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) PutTrack(ctx context.Context, in *PutTrackRequest, opts ...grpc.CallOption) (*PutTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutTrackResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_PutTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) GetTracks(ctx context.Context, in *GetTracksRequest, opts ...grpc.CallOption) (*GetTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTracksResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_GetTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) PutCommand(ctx context.Context, in *PutCommandRequest, opts ...grpc.CallOption) (*PutCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutCommandResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_PutCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) GetCommands(ctx context.Context, in *GetCommandsRequest, opts ...grpc.CallOption) (*GetCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommandsResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_GetCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DocumentChange], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PeatSidecar_ServiceDesc.Streams[0], PeatSidecar_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, DocumentChange]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeatSidecar_SubscribeClient = grpc.ServerStreamingClient[DocumentChange]

func (c *peatSidecarClient) StartSync(ctx context.Context, in *StartSyncRequest, opts ...grpc.CallOption) (*StartSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSyncResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_StartSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) StopSync(ctx context.Context, in *StopSyncRequest, opts ...grpc.CallOption) (*StopSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSyncResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_StopSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) GetSyncStats(ctx context.Context, in *GetSyncStatsRequest, opts ...grpc.CallOption) (*GetSyncStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncStatsResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_GetSyncStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) SendAttachments(ctx context.Context, in *SendAttachmentsRequest, opts ...grpc.CallOption) (*SendAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendAttachmentsResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_SendAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) GetAttachmentDistribution(ctx context.Context, in *GetAttachmentDistributionRequest, opts ...grpc.CallOption) (*GetAttachmentDistributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttachmentDistributionResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_GetAttachmentDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) SubscribeAttachmentBundle(ctx context.Context, in *SubscribeAttachmentBundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AttachmentProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PeatSidecar_ServiceDesc.Streams[1], PeatSidecar_SubscribeAttachmentBundle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeAttachmentBundleRequest, AttachmentProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeatSidecar_SubscribeAttachmentBundleClient = grpc.ServerStreamingClient[AttachmentProgress]

func (c *peatSidecarClient) CancelAttachmentDistribution(ctx context.Context, in *CancelAttachmentDistributionRequest, opts ...grpc.CallOption) (*CancelAttachmentDistributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAttachmentDistributionResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_CancelAttachmentDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) SetCollectionConfig(ctx context.Context, in *SetCollectionConfigRequest, opts ...grpc.CallOption) (*SetCollectionConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCollectionConfigResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_SetCollectionConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) GetCollectionConfig(ctx context.Context, in *GetCollectionConfigRequest, opts ...grpc.CallOption) (*GetCollectionConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectionConfigResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_GetCollectionConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peatSidecarClient) ListCollectionConfigs(ctx context.Context, in *ListCollectionConfigsRequest, opts ...grpc.CallOption) (*ListCollectionConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionConfigsResponse)
	err := c.cc.Invoke(ctx, PeatSidecar_ListCollectionConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeatSidecarServer is the server API for PeatSidecar service.
// All implementations must embed UnimplementedPeatSidecarServer
// for forward compatibility.
//
// PeatSidecar exposes Peat mesh participation to co-located applications
// over gRPC (Unix socket or TCP). The sidecar is a full CRDT mesh participant;
// client applications interact with it to read/write shared state.
type PeatSidecarServer interface {
	// GetStatus returns the current state of the sidecar node.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// ConnectPeer establishes an authenticated connection to a mesh peer.
	ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error)
	// DisconnectPeer drops the connection to a peer.
	DisconnectPeer(context.Context, *DisconnectPeerRequest) (*DisconnectPeerResponse, error)
	// ListPeers returns currently connected peers.
	ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error)
	// PutDocument creates or updates a document in a collection.
	PutDocument(context.Context, *PutDocumentRequest) (*PutDocumentResponse, error)
	// GetDocument retrieves a document by collection and ID.
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	// DeleteDocument removes a document from a collection.
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	// ListDocuments lists all document IDs in a collection.
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	PutNode(context.Context, *PutNodeRequest) (*PutNodeResponse, error)
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	PutCell(context.Context, *PutCellRequest) (*PutCellResponse, error)
	GetCells(context.Context, *GetCellsRequest) (*GetCellsResponse, error)
	PutTrack(context.Context, *PutTrackRequest) (*PutTrackResponse, error)
	GetTracks(context.Context, *GetTracksRequest) (*GetTracksResponse, error)
	PutCommand(context.Context, *PutCommandRequest) (*PutCommandResponse, error)
	GetCommands(context.Context, *GetCommandsRequest) (*GetCommandsResponse, error)
	// Subscribe streams document changes across all or filtered collections.
	//
	// The server sends an initial snapshot of all currently-stored matching
	// documents as CHANGE_TYPE_UPSERT events, then streams live changes.
	// Clients can distinguish snapshot from live events by consuming until
	// the server indicates readiness, or by treating all Upserts idempotently.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[DocumentChange]) error
	// StartSync begins CRDT synchronization with connected peers.
	StartSync(context.Context, *StartSyncRequest) (*StartSyncResponse, error)
	// StopSync pauses synchronization.
	StopSync(context.Context, *StopSyncRequest) (*StopSyncResponse, error)
	// GetSyncStats returns current synchronization statistics.
	GetSyncStats(context.Context, *GetSyncStatsRequest) (*GetSyncStatsResponse, error)
	// SendAttachments ingests one or more local files and queues them for
	// distribution to the specified scope. Each file is validated (size, hash,
	// path inside an allowlisted root) before any blob is created — partial
	// ingestion is not allowed. Returns synchronously with handles; transfer
	// happens asynchronously.
	//
	// Safety default: with no `--attachment-root` configured on peat-node, this
	// RPC returns UNIMPLEMENTED. Operators must consciously opt in by naming
	// the roots that may be read.
	SendAttachments(context.Context, *SendAttachmentsRequest) (*SendAttachmentsResponse, error)
	// GetAttachmentDistribution returns the current status of a single
	// distribution by its ID. Returns NOT_FOUND with the offending
	// distribution_id in the error detail when the ID is unknown.
	GetAttachmentDistribution(context.Context, *GetAttachmentDistributionRequest) (*GetAttachmentDistributionResponse, error)
	// SubscribeAttachmentBundle streams progress updates for every distribution
	// in a bundle until all reach a terminal state or the client disconnects.
	//
	// Late-subscribe semantics (for crash-recovery):
	//   - All-terminal at subscribe time (every distribution already in
	//     COMPLETED / FAILED / CANCELLED): the server emits exactly one
	//     AttachmentProgress snapshot per distribution carrying that terminal
	//     state, then closes the stream.
	//   - Mixed state at subscribe time (some distributions already terminal,
	//     others still PENDING / IN_PROGRESS): the server emits one snapshot
	//     for each already-terminal distribution first, then streams live
	//     progress updates for the in-flight distributions, then closes once
	//     every distribution has reached a terminal state.
	//   - All-live at subscribe time (no terminal distributions yet): live
	//     streaming only — no synthetic snapshots — until terminal close.
	//
	// The late-subscribe contract covers *client* crashes. A *server*
	// (peat-node) restart drops the in-memory handle table; resubscribing to
	// a pre-restart bundle_id returns NOT_FOUND.
	SubscribeAttachmentBundle(*SubscribeAttachmentBundleRequest, grpc.ServerStreamingServer[AttachmentProgress]) error
	// CancelAttachmentDistribution requests cancellation of an in-flight
	// distribution. Best-effort; already-transferred bytes on receivers are
	// not rolled back. Returns NOT_FOUND when distribution_id is unknown.
	CancelAttachmentDistribution(context.Context, *CancelAttachmentDistributionRequest) (*CancelAttachmentDistributionResponse, error)
	// SetCollectionConfig persists deletion-policy and TTL settings for a named
	// collection. Settings survive node restarts. Applying a new config to an
	// existing collection replaces the prior config wholesale.
	SetCollectionConfig(context.Context, *SetCollectionConfigRequest) (*SetCollectionConfigResponse, error)
	// GetCollectionConfig returns the explicit config for a collection.
	// Returns NOT_FOUND when no config has been set (the default policy applies).
	GetCollectionConfig(context.Context, *GetCollectionConfigRequest) (*GetCollectionConfigResponse, error)
	// ListCollectionConfigs returns all explicitly configured collections.
	// Collections using the default policy are not included.
	ListCollectionConfigs(context.Context, *ListCollectionConfigsRequest) (*ListCollectionConfigsResponse, error)
	mustEmbedUnimplementedPeatSidecarServer()
}

// UnimplementedPeatSidecarServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeatSidecarServer struct{}

func (UnimplementedPeatSidecarServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPeatSidecarServer) ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectPeer not implemented")
}
func (UnimplementedPeatSidecarServer) DisconnectPeer(context.Context, *DisconnectPeerRequest) (*DisconnectPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectPeer not implemented")
}
func (UnimplementedPeatSidecarServer) ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedPeatSidecarServer) PutDocument(context.Context, *PutDocumentRequest) (*PutDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutDocument not implemented")
}
func (UnimplementedPeatSidecarServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedPeatSidecarServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedPeatSidecarServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedPeatSidecarServer) PutNode(context.Context, *PutNodeRequest) (*PutNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutNode not implemented")
}
func (UnimplementedPeatSidecarServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedPeatSidecarServer) PutCell(context.Context, *PutCellRequest) (*PutCellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutCell not implemented")
}
func (UnimplementedPeatSidecarServer) GetCells(context.Context, *GetCellsRequest) (*GetCellsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCells not implemented")
}
func (UnimplementedPeatSidecarServer) PutTrack(context.Context, *PutTrackRequest) (*PutTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutTrack not implemented")
}
func (UnimplementedPeatSidecarServer) GetTracks(context.Context, *GetTracksRequest) (*GetTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTracks not implemented")
}
func (UnimplementedPeatSidecarServer) PutCommand(context.Context, *PutCommandRequest) (*PutCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutCommand not implemented")
}
func (UnimplementedPeatSidecarServer) GetCommands(context.Context, *GetCommandsRequest) (*GetCommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommands not implemented")
}
func (UnimplementedPeatSidecarServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[DocumentChange]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPeatSidecarServer) StartSync(context.Context, *StartSyncRequest) (*StartSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSync not implemented")
}
func (UnimplementedPeatSidecarServer) StopSync(context.Context, *StopSyncRequest) (*StopSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSync not implemented")
}
func (UnimplementedPeatSidecarServer) GetSyncStats(context.Context, *GetSyncStatsRequest) (*GetSyncStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncStats not implemented")
}
func (UnimplementedPeatSidecarServer) SendAttachments(context.Context, *SendAttachmentsRequest) (*SendAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAttachments not implemented")
}
func (UnimplementedPeatSidecarServer) GetAttachmentDistribution(context.Context, *GetAttachmentDistributionRequest) (*GetAttachmentDistributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttachmentDistribution not implemented")
}
func (UnimplementedPeatSidecarServer) SubscribeAttachmentBundle(*SubscribeAttachmentBundleRequest, grpc.ServerStreamingServer[AttachmentProgress]) error {
	return status.Error(codes.Unimplemented, "method SubscribeAttachmentBundle not implemented")
}
func (UnimplementedPeatSidecarServer) CancelAttachmentDistribution(context.Context, *CancelAttachmentDistributionRequest) (*CancelAttachmentDistributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAttachmentDistribution not implemented")
}
func (UnimplementedPeatSidecarServer) SetCollectionConfig(context.Context, *SetCollectionConfigRequest) (*SetCollectionConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCollectionConfig not implemented")
}
func (UnimplementedPeatSidecarServer) GetCollectionConfig(context.Context, *GetCollectionConfigRequest) (*GetCollectionConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollectionConfig not implemented")
}
func (UnimplementedPeatSidecarServer) ListCollectionConfigs(context.Context, *ListCollectionConfigsRequest) (*ListCollectionConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollectionConfigs not implemented")
}
func (UnimplementedPeatSidecarServer) mustEmbedUnimplementedPeatSidecarServer() {}
func (UnimplementedPeatSidecarServer) testEmbeddedByValue()                     {}

// UnsafePeatSidecarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeatSidecarServer will
// result in compilation errors.
type UnsafePeatSidecarServer interface {
	mustEmbedUnimplementedPeatSidecarServer()
}

func RegisterPeatSidecarServer(s grpc.ServiceRegistrar, srv PeatSidecarServer) {
	// If the following call panics, it indicates UnimplementedPeatSidecarServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeatSidecar_ServiceDesc, srv)
}

func _PeatSidecar_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_ConnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).ConnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_ConnectPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).ConnectPeer(ctx, req.(*ConnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_DisconnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).DisconnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_DisconnectPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).DisconnectPeer(ctx, req.(*DisconnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_PutDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).PutDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_PutDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).PutDocument(ctx, req.(*PutDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_PutNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).PutNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_PutNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).PutNode(ctx, req.(*PutNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_PutCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).PutCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_PutCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).PutCell(ctx, req.(*PutCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_GetCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).GetCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_GetCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).GetCells(ctx, req.(*GetCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_PutTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).PutTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_PutTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).PutTrack(ctx, req.(*PutTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_GetTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).GetTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_GetTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).GetTracks(ctx, req.(*GetTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_PutCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).PutCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_PutCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).PutCommand(ctx, req.(*PutCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_GetCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).GetCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_GetCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).GetCommands(ctx, req.(*GetCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PeatSidecarServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, DocumentChange]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeatSidecar_SubscribeServer = grpc.ServerStreamingServer[DocumentChange]

func _PeatSidecar_StartSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).StartSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_StartSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).StartSync(ctx, req.(*StartSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_StopSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).StopSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_StopSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).StopSync(ctx, req.(*StopSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_GetSyncStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).GetSyncStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_GetSyncStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).GetSyncStats(ctx, req.(*GetSyncStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_SendAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).SendAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_SendAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).SendAttachments(ctx, req.(*SendAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_GetAttachmentDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttachmentDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).GetAttachmentDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_GetAttachmentDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).GetAttachmentDistribution(ctx, req.(*GetAttachmentDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_SubscribeAttachmentBundle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeAttachmentBundleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PeatSidecarServer).SubscribeAttachmentBundle(m, &grpc.GenericServerStream[SubscribeAttachmentBundleRequest, AttachmentProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PeatSidecar_SubscribeAttachmentBundleServer = grpc.ServerStreamingServer[AttachmentProgress]

func _PeatSidecar_CancelAttachmentDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAttachmentDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).CancelAttachmentDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_CancelAttachmentDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).CancelAttachmentDistribution(ctx, req.(*CancelAttachmentDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_SetCollectionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCollectionConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).SetCollectionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_SetCollectionConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).SetCollectionConfig(ctx, req.(*SetCollectionConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_GetCollectionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).GetCollectionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_GetCollectionConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).GetCollectionConfig(ctx, req.(*GetCollectionConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeatSidecar_ListCollectionConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeatSidecarServer).ListCollectionConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeatSidecar_ListCollectionConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeatSidecarServer).ListCollectionConfigs(ctx, req.(*ListCollectionConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeatSidecar_ServiceDesc is the grpc.ServiceDesc for PeatSidecar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeatSidecar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peat.sidecar.v1.PeatSidecar",
	HandlerType: (*PeatSidecarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _PeatSidecar_GetStatus_Handler,
		},
		{
			MethodName: "ConnectPeer",
			Handler:    _PeatSidecar_ConnectPeer_Handler,
		},
		{
			MethodName: "DisconnectPeer",
			Handler:    _PeatSidecar_DisconnectPeer_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _PeatSidecar_ListPeers_Handler,
		},
		{
			MethodName: "PutDocument",
			Handler:    _PeatSidecar_PutDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _PeatSidecar_GetDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _PeatSidecar_DeleteDocument_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _PeatSidecar_ListDocuments_Handler,
		},
		{
			MethodName: "PutNode",
			Handler:    _PeatSidecar_PutNode_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _PeatSidecar_GetNodes_Handler,
		},
		{
			MethodName: "PutCell",
			Handler:    _PeatSidecar_PutCell_Handler,
		},
		{
			MethodName: "GetCells",
			Handler:    _PeatSidecar_GetCells_Handler,
		},
		{
			MethodName: "PutTrack",
			Handler:    _PeatSidecar_PutTrack_Handler,
		},
		{
			MethodName: "GetTracks",
			Handler:    _PeatSidecar_GetTracks_Handler,
		},
		{
			MethodName: "PutCommand",
			Handler:    _PeatSidecar_PutCommand_Handler,
		},
		{
			MethodName: "GetCommands",
			Handler:    _PeatSidecar_GetCommands_Handler,
		},
		{
			MethodName: "StartSync",
			Handler:    _PeatSidecar_StartSync_Handler,
		},
		{
			MethodName: "StopSync",
			Handler:    _PeatSidecar_StopSync_Handler,
		},
		{
			MethodName: "GetSyncStats",
			Handler:    _PeatSidecar_GetSyncStats_Handler,
		},
		{
			MethodName: "SendAttachments",
			Handler:    _PeatSidecar_SendAttachments_Handler,
		},
		{
			MethodName: "GetAttachmentDistribution",
			Handler:    _PeatSidecar_GetAttachmentDistribution_Handler,
		},
		{
			MethodName: "CancelAttachmentDistribution",
			Handler:    _PeatSidecar_CancelAttachmentDistribution_Handler,
		},
		{
			MethodName: "SetCollectionConfig",
			Handler:    _PeatSidecar_SetCollectionConfig_Handler,
		},
		{
			MethodName: "GetCollectionConfig",
			Handler:    _PeatSidecar_GetCollectionConfig_Handler,
		},
		{
			MethodName: "ListCollectionConfigs",
			Handler:    _PeatSidecar_ListCollectionConfigs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PeatSidecar_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeAttachmentBundle",
			Handler:       _PeatSidecar_SubscribeAttachmentBundle_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "peat/sidecar/v1/sidecar.proto",
}
