apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-portal.fullname" . }}
  labels:
    {{- include "keycloak-portal.labels" . | nindent 4 }}
data:
  LISTEN_ADDR: {{ .Values.config.listenAddr | quote }}
  OIDC_CLIENT_ID: {{ .Values.config.clientId | quote }}
  {{- if .Values.uds.enabled }}
  KEYCLOAK_ISSUER: {{ include "keycloak-portal.udsIssuer" . | quote }}
  OIDC_REDIRECT_URL: {{ printf "https://%s/auth/callback" (include "keycloak-portal.udsFullHost" .) | quote }}
  OIDC_POST_LOGOUT_REDIRECT_URL: {{ printf "https://%s/" (include "keycloak-portal.udsFullHost" .) | quote }}
  {{- else }}
  KEYCLOAK_ISSUER: {{ .Values.config.issuer | quote }}
  OIDC_REDIRECT_URL: {{ .Values.config.redirectUrl | quote }}
  OIDC_POST_LOGOUT_REDIRECT_URL: {{ .Values.config.postLogoutRedirectUrl | quote }}
  {{- end }}
  OIDC_SCOPES: {{ .Values.config.scopes | quote }}
  COOKIE_SECURE: {{ .Values.config.cookieSecure | quote }}
  ADMIN_GROUP: {{ .Values.config.adminGroup | quote }}
  PEAT_NODE_ADDR: {{ .Values.config.peatNodeAddr | quote }}
  PEAT_COLLECTION: {{ .Values.config.peatCollection | quote }}
  PEAT_TLS: {{ .Values.config.peatTls | quote }}
