{{- if not .Values.clientSecret.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-portal.fullname" . }}
  labels:
    {{- include "keycloak-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ required "clientSecret.value is required when clientSecret.existingSecret.name is not set" .Values.clientSecret.value | quote }}
{{- end }}
